stages:
- build_scanners
- build_backends
- build_gambit
- check

variables:
  LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH


.build_template: &build_template
  image:
    gambitbsm/gambit-base:$OS
  script:
    - export CMAKE_BUILD_TYPE=None
    - export CMAKE_C_COMPILER=`which gcc`
    - export CMAKE_CXX_COMPILER=`which g++`
    - export CMAKE_Fortran_COMPILER=`which gfortran`
    - export PYTHON_EXECUTABLE=`which python`
    - export PYTHON_LIBRARY=`python -c 'from __future__ import print_function; from distutils.sysconfig import get_config_var; print("%s/%s" % (get_config_var("LIBDIR"), get_config_var("INSTSONAME")))'`
    - export PYTHON_INCLUDE_DIR=`python -c 'from __future__ import print_function; from distutils import sysconfig; print(sysconfig.get_config_var("INCLUDEPY"))'`
    - mkdir -p BUILD && cd BUILD
    - cmake .. -D WITH_ROOT=ON -D WITH_RESTFRAMES=ON -D WITH_HEPMC=ON -D BUILD_FS_MODELS=MDM
    - make $TARGET -j`nproc --ignore=2`
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/BUILD
    expire_in: 1 week


scanners_ubuntu:
  variables:
    OS: ubuntu
    TARGET: scanners
  stage: build_scanners
  <<: *build_template

backends_ubuntu:
  variables:
    OS: ubuntu
    TARGET: backends
  stage: build_backends
  <<: *build_template
  needs:
    - scanners_ubuntu

gambit_ubuntu:
  variables:
    OS: ubuntu
    TARGET: gambit
  stage: build_gambit
  <<: *build_template
  needs:
    - scanners_ubuntu
    - backends_ubuntu


scanners_fedora:
  variables:
    OS: fedora
    TARGET: scanners
  stage: build_scanners
  <<: *build_template

backends_fedora:
  variables:
    OS: fedora
    TARGET: backends
  stage: build_backends
  <<: *build_template
  needs:
    - scanners_fedora

gambit_fedora:
  variables:
    OS: fedora
    TARGET: gambit
  stage: build_gambit
  <<: *build_template
  needs:
    - scanners_fedora
    - backends_fedora



# TODO: template on OS
validate:
  image:
    gambitbsm/gambit-base:ubuntu
  stage: check
  script:
    - apt-get -y update
    - apt-get -y install git python python-yaml cowsay bats numdiff
    - cowsay "Testing GAMBIT on $(date)"
    - cowsay "$(git log -n 5)"
    ## Get BATS tests and notify re. updates
    - git clone https://github.com/GambitBSM/gambit_bats.git
    - cd gambit_bats
    - git pull
    - cowsay "$(git log -n 5)"
    - rm -f ../bats.tap
    - export GAMBIT="$PWD/../"
    ## Pipe test results to file for JENKINS
    - bats --tap *.bats > ../bats.tap
    - cd ..
    ## Note email addresses for failed tests
    - source gambit_bats/email.bash
    - export BATS_FAIL_EMAIL=$(bats_fail_email ./bats.tap)
    - export GIT_FAIL_EMAIL="$(git_fail_email ./gambit_bats) $(git_fail_email ./)"
    - cowsay "For BATS yaml failures, contact $BATS_FAIL_EMAIL"
    - cowsay "For GAMBIT and test changes, contact $GIT_FAIL_EMAIL"
  needs:
    - scanners_ubuntu
    - backends_ubuntu
    - gambit_ubuntu
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/gambit_bats
    expire_in: 1 week
