##########################################################################
## GAMBIT configuration for a minimal postprocessor (version 2) run
##
## Requires 'spartan.yaml' to be run first, as this will generate the 
## data that we will postprocess.
##
##########################################################################


Parameters:
  # In this example we will simply be fitting the mean and standard deviation of a normal distribution.
  NormalDist:
    mu:
      prior_type: none
    sigma:
      prior_type: none
 
Priors:

  # None used

Printer:

  printer: hdf5
  options:
    output_file: "pp_results.hdf5"
    group: "/ppv2"
    delete_file_on_restart: true

Scanner:

  use_scanner: postprocessor

  scanners:

    postprocessor:
      plugin: postprocessor
      #version: "1.0" 
       # Name of the new global likelihood contribution.
      like: New_LogLike
      # Name of the combined new+old likelihood
      reweighted_like: Comb_LogLike
      # Add LogLike in the old output to New_LogLike in the new output.   
      add_to_like: [LogLike]                                             
      # Allow overwriting of the old output with the new output (e.g. if you would rather name New_LogLike as LogLike)
      permit_discard_old_likes: false
      update_interval: 1000 # Frequency to print status update message
      batch_size: 100 # Number of points to distribute to worker processes each time they request more work
      # The below don't seem to work?
      # Restrict postprocessing to values greater than this
      # cut_greater_than: {"LogLike": -68.5843} # best fit - 5sigma
      # Throw away all points outside the cuts
      # discard_points_outside_cuts: true
      # Information about input dataset to be postprocessed
      reader:
        type: hdf5
        file: "runs/spartan/samples/results.hdf5"
        group: "/spartan"

ObsLikes:

    # Test normal distribution likelihood
  - purpose:      New_LogLike
    capability:   normaldist_loglike
    module:       ExampleBit_A
    type:         double


Rules:

  - capability: normaldist_loglike
    function: lnL_gaussian
    options:
       # Set sleep time between evaluations (in seconds)
       #eval_time: 0.01

Logger:

  redirection:
    [Default]      : "default.log"
    [ExampleBit_A] : "ExampleBit_A.log"
    [Scanner]      : "Scanner.log"


KeyValues:

  default_output_path: "runs/postprocessor_v2"

  rng: ranlux48

  print_timing_data: false

  likelihood:
    model_invalid_for_lnlike_below: -1e6
