##########################################################################
## GAMBIT configuration for a postprocessor run in which MSSM spectrum
## info is retrieved from a previous output file, and used for new
## calculations.
##
##########################################################################


Parameters:
  
  # Parameters to be read from the input data file need to have prior_type: none.
  #CMSSM:
  #  A0:
  #    prior_type: none
  #  M0:
  #    prior_type: none
  #  M12:
  #    prior_type: none
  #  SignMu:
  #    prior_type: none
  #  TanBeta:
  #    prior_type: none

  # For EWMSSM version:
  MSSM11atQ_mA:
    Ad_3:
      prior_type: none
    Ae_3:
      prior_type: none
    Au_3:
      prior_type: none
    M1:
      prior_type: none
    M2:
      prior_type: none
    M3:
      prior_type: none
    Qin:
      prior_type: none
    TanBeta:
      prior_type: none
    mA:
      prior_type: none
    ml2:
      prior_type: none
    mq2:
      prior_type: none
    mu:
      prior_type: none

  StandardModel_SLHA2: !import include/StandardModel_SLHA2_postprocessing.yaml

Priors:

  # None used

Printer:

  printer: hdf5
  options:
    output_file: "spectrum_pp_results.hdf5"
    group: "/spec_pp"
    delete_file_on_restart: true
    buffer_length: 1

  #printer: sqlite
  #options:
  #  output_file: "pp_results.sql"
  #  table_name: "ppv2"
  #  buffer_length: 100
  #  delete_file_on_restart: true

Scanner:

  use_scanner: postprocessor

  scanners:

    postprocessor:
      plugin: postprocessor
      # 'purpose' label of new likelihood contributions 
      like: New_LogLike
      # Name of the combined new+old likelihood
      reweighted_like: Comb_LogLike
      # Allow overwriting of the old output with the new output (e.g. if you would rather name New_LogLike as LogLike)
      permit_discard_old_likes: true
      update_interval: 10 # Frequency to print status update message
      batch_size: 100 # Number of points to distribute to worker processes each time they request more work
      #Throw away all points outside the cuts
      #discard_points_outside_cuts: true
      # Information about input dataset to be postprocessed
      reader:
        type: hdf5
        # CMSSM version
        #file: "/home/farmer/tmp/Janina_dataset/crash_test/VS-resume/samples/CMSSM_VS_Result.hdf5"
        #group: "/CMSSM"
        # EWMSSM version
        file: "/home/farmer/repos/jpvc_analyses/data/MSSMEW_pp_final.hdf5"
        group: "/MSSMEW"


ObsLikes:

    # Recalculate some stuff that needs an MSSM spectrum
     
    # Flavour physics likelihoods
    - purpose:    LogLike
      capability: b2ll_LL

    - purpose:    LogLike
      capability: SL_LL

    - purpose:    LogLike
      capability: b2sll_LL

    - purpose:    LogLike
      capability: b2sgamma_LL

    - purpose:    LogLike
      capability: LUV_LL

    # Precision physics likelihoods
    - capability: lnL_W_mass
      purpose:    LogLike

    # Print spectrum
    - capability: MSSM_spectrum
      purpose:    Observable
      type:       map_str_dbl

Rules:

  - capability: unimproved_MSSM_spectrum
    function: get_MSSM_spectrum_from_postprocessor
    type: Spectrum

  # Choose where to get the precision spectrum from
  # (No modification of retrieved spectrum)
  - capability: MSSM_spectrum
    type: Spectrum
    function: make_MSSM_precision_spectrum_none

  # Use SuperIso for flavour likelihoods
  - capability: bsgamma
    function: SI_bsgamma

  - capability: Bsmumu_untag
    function: SI_Bsmumu_untag



Logger:

  redirection:
    [Default]      : "default.log"
    [ExampleBit_A] : "ExampleBit_A.log"
    [Scanner]      : "Scanner.log"


KeyValues:

  default_output_path: "runs/spectrum_retrieve_demo"

  rng:
    generator: ranlux48
    seed: -1

  print_timing_data: false

  likelihood:
    model_invalid_for_lnlike_below: -1e6
