//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Py8Collider typedefs for models in           
///  ColliderBit.                                 
///                                               
///  This file is automatically generated by      
///  collider_harvester.py.  Do not modify.       
///                                               
///  *********************************************
///                                               
///  \author The GAMBIT Collaboration            
///  \date 07:01AM on March 10, 2022
///                                               
///  *********************************************
                                                  
#pragma once                                      
                                                  
#include "gambit/ColliderBit/colliders/Pythia8/Py8Collider.hpp"
                                                  
namespace Gambit                                  
{                                                 
  namespace ColliderBit                           
  {                                               
                                                  
    /// Typedefs for each Pythia collider         
    /// @{                                        
    #ifdef EXCLUDE_HEPMC                          
      typedef Py8Collider<Pythia_default::Pythia8::Pythia, Pythia_default::Pythia8::Event, void> Py8Collider_defaultversion;
    #else                                         
      typedef Py8Collider<Pythia_default::Pythia8::Pythia, Pythia_default::Pythia8::Event, Pythia_default::Pythia8::GAMBIT_hepmc_writer> Py8Collider_defaultversion;
    #endif
    /// @}

  }
}
