#ifndef __wrapper_DM_Detector_Ionization_Migdal_obscura_1_0_2_hpp__
#define __wrapper_DM_Detector_Ionization_Migdal_obscura_1_0_2_hpp__


#include "wrapper_DM_Detector_Ionization_Migdal_decl.hpp"
#include "wrapper_DM_Detector_Ionization_Migdal_def.hpp"


#endif /* __wrapper_DM_Detector_Ionization_Migdal_obscura_1_0_2_hpp__ */
