name: Gambit CI

on:
  push:
    branches: [ gitlab-ci ]
  pull_request:
    branches: [ gitlab-ci ]

jobs:
  gambit_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ubuntu] #, fedora]
        #mpi: [on, off]
    container: gambitbsm/gambit-base:${{ matrix.arch }}
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
    - uses: actions/checkout@v2
    - name: Ubuntu HDF5 clean
      if: ${{ matrix.os == 'ubuntu' }}
      run: |
        apt-get remove libhdf5-openmpi-dev
        apt-get install libhdf5-dev
    - name: Set up build environment
      run: |
        mkdir -p BUILD
        cd BUILD
        . /etc/profile
        > buildenv.sh
        echo ". /etc/profile" >> buildenv.sh
        echo "export CMAKE_BUILD_TYPE=None" >> buildenv.sh
        echo "export CMAKE_C_COMPILER=$(which mpicc)" >> buildenv.sh
        echo "export CMAKE_CXX_COMPILER=$(which mpic++)" >> buildenv.sh
        echo "export CMAKE_Fortran_COMPILER=$(which mpifort)" >> buildenv.sh
        PYTHON_LIBRARY=$(python -c 'from __future__ import print_function; from distutils.sysconfig import get_config_var; print("%s/%s" % (get_config_var("LIBDIR"), get_config_var("INSTSONAME")))')
        PYTHON_INCLUDE_DIR=$(python -c 'from __future__ import print_function; from distutils import sysconfig; print(sysconfig.get_config_var("INCLUDEPY"))')
        echo "export PYTHON_EXECUTABLE=$(which python)" >> buildenv.sh
        echo "export PYTHON_LIBRARY=$PYTHON_LIBRARY" >> buildenv.sh
        echo "export PYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR" >> buildenv.sh
        echo "export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH" >> buildenv.sh
        cat buildenv.sh
    - name: Build scanners
      run: |
        cd BUILD/ && . buildenv.sh
        cmake .. -D WITH_ROOT=ON -D WITH_RESTFRAMES=ON -D WITH_HEPMC=ON -D BUILD_FS_MODELS=MDM -D WITH_MPI=OFF
        make -j$(nproc) scanners
        cmake .. -D WITH_ROOT=ON -D WITH_RESTFRAMES=ON -D WITH_HEPMC=ON -D BUILD_FS_MODELS=MDM -D WITH_MPI=OFF
    - name: Build backends
      run: |
        cd BUILD && . buildenv.sh
        make -j$(nproc) backends
    - name: Build Gambit
      run: |
        cd BUILD && . buildenv.sh
        make -j$(nproc) gambit
    - name: Validate with BATS
      run: |
        . BUILD/buildenv.sh
        apt-get -y update
        apt-get -y install git python python-yaml cowsay bats numdiff
        cowsay "Testing GAMBIT on $(date)"
        cowsay "$(git log -n 5)"
        # Get BATS tests and notify re. updates
        git clone https://github.com/GambitBSM/gambit_bats.git
        cd gambit_bats
        git pull
        cowsay "$(git log -n 5)"
        rm -f ../bats.tap
        export GAMBIT="$PWD/../"
        # Pipe test results to file for JENKINS
        bats --tap *.bats > ../bats.tap
        cd ..
        # Note email addresses for failed tests
        source gambit_bats/email.bash
        export BATS_FAIL_EMAIL=$(bats_fail_email ./bats.tap)
        export GIT_FAIL_EMAIL="$(git_fail_email ./gambit_bats) $(git_fail_email ./)"
        cowsay "For BATS yaml failures, contact $BATS_FAIL_EMAIL"
        cowsay "For GAMBIT and test changes, contact $GIT_FAIL_EMAIL"
