name: Gambit CI

on:
  push:
    branches: [ NewRunners ]
  pull_request:
    branches: [ NewRunners ]
  schedule:
    - cron:  '0 5 * * *'

jobs:
  gambit_build:
    runs-on: [self-hosted, macOS, X64]
    strategy:
      fail-fast: false
      matrix:
        arch: [x64] #, fedora
    #defaults:
    #  run:
    #    shell: bash -eo pipefail {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up build environment
      run: |
        echo "Here I would set up the build environment"
        mkdir -p BUILD
        cd BUILD
    - name: Configure with cmake
      run: |
        echo "First Testing with a ditched ColliderBit"
        cd BUILD
        cmake -Ditch="ColliderBit" ..
    - name: Build scanners
      run: |
        echo "Here I would build the scanners"
        #cd BUILD
        #make scanners
        #cmake ..
    - name: Build Gambit
      run: |
        echo "Here I would build GAMBIT."
        cd BUILD
        make -j8 gambit
    - name: Test spartan yaml
      run: |
        ./gambit -rf yaml_files/spartan.yaml 
    - name: Build backends
      run: |
         echo "Here I would build all the backends (in serial)"
    - name: CLI test
      run: |
        echo "Here I would run the test of gambit help"
    - name: WC test
      run: |
        echo "Here I would test the run of the WC_lite yaml"
    - name: ColliderBit test
      run: |
        echo "Here I would test the ColliderBit CMSSM yaml file"
    - name: Build standalones
      run: |
        echo "Here I would test the building of the standalones"
    - name: Build and Run GUM
      run: |
        echo "Here I would test GUM"
